services:
  jira_cli_tool:
    build: .  # build from Dockerfile in current directory
    image: jira_summary_tool:latest
    environment:
      JIRA_SERVER: "xxx"
      JIRA_USER: "xxx"           # taken from host env, for example
      JIRA_API_TOKEN: "xxx"
      COHERE_API_KEY: "xxx"
      MODE: "production"
    volumes:
      - ./outputs:/outputs
      # - ./jira_summary/logs:/app/logs
    # The command can be overridden when running `docker-compose run`
    # For example: docker-compose run jira_cli_tool --project MYPROJ
